### ISSUE TITLE
sponsoredAd all false?

### ISSUE THREAD

**Issue by 4ever911** [proxycrawl/proxycrawl-python#12]
When i do a serp request like 

curl 'https://api.crawlbase.com/?token=TOKENTOKENTOKENTOKEN&url=https://www.amazon.co.uk/s?k=iphone+14+case&scraper=amazon-serp&device=mobile&country=GB'

the result jason returnes a list of product which are all organic products. there is no sponsored ads products in that.

is there anything i am doing wrong?

**Comment by crawlbase** [comment]
Hello,
As we have checked, you already sent this inquiry to our support team from the dashboard. Since this issue is not related to the library itself, our experts will contact you via email to provide a solution as soon as possible. I'm closing this issue not to confuse our technical team, as is not a direct problem with the library.
